name: Build Your CV

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: crackedngineer/codeurcv-action@v0.3.4
        with:
          config-path: Subhomoy_Roy_Choudhury_CV.yml
          out-dir: output
          filename: Subhomoy_Roy_Choudhury_4YoE_CV
