name: Build Your CV

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: crackedngineer/codeurcv-action@v0.3.1
        with:
          config-path: config.yml
          out-dir: output
          template: minimalist
          filename: Subhomoy_Roy_Choudhury_SE2_4YoE
